version: '2'
services:
  mysql55:
    container_name: mysql55
    image: mysql:5.5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASSWORD}
    networks:
      - dev_stack_net
    volumes:
      - "$PWD/data/qa:/var/lib/mysql"
      - "$PWD/data/qa/init:/docker-entrypoint-initdb.d"
    labels:
      traefik.enable: "false"

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:3.1.0
    expose:
      - 4444
      - 9625
    ports:
      - "4444:4444"
    networks:
      dev_stack_net:
        ipv4_address: 172.80.0.42
    labels:
      traefik.enable: "false"

  traefik:
    container_name: reverse-proxy
    image: traefik
    command: --web --docker --logLevel=DEBUG
    expose:
      - 80
      - 8080
      - 443
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.toml:/traefik.toml"
    networks:
      dev_stack_net:
        ipv4_address: 172.80.0.10 # We want a fix IP for a authentication control to the App
    labels:
      traefik.enable: "false"

  beanstalk:
    container_name: beanstalk
    image: schickling/beanstalkd:latest
    expose:
      - 11300
    command: ["-p", "11300", "-z", "134217728"]
    ports:
      - "11300:11300"
    networks:
      - dev_stack_net
    labels:
      traefik.enable: "false"

  # Not used for the moment

  #  influxdb:
  #    image: tutum/influxdb
  #    ports:
  #      - "8083:8083"
  #      - "8086:8086"
  #    volumes:
  #      - "$PWD/data/influxdb:/data"
  #    environment:
  #      PRE_CREATE_DB: "instrument"
  #    networks:
  #      - dev_stack_net
  #    labels:
  #      traefik.enable: "false"
  #
  #  grafana:
  #    image: grafana/grafana
  #    ports:
  #      - "3000:3000"
  #    volumes:
  #      - "$PWD/data/grafana:/var/lib/grafana"
  #    networks:
  #      - dev_stack_net
  #    labels:
  #      traefik.enable: "false"

  memcached:
    image: memcached:latest
    expose:
      - 11211
    networks:
      - dev_stack_net

  memcached2:
    image: memcached:latest
    expose:
      - 11211
    networks:
      - dev_stack_net

  beanstalk_console:
    image: kusmierz/beanstalk-console
    networks:
      - dev_stack_net
    expose:
      - 80
    labels:
      traefik.frontend.rule: "Host:beanstalk-console.local"
      traefik.backend: "beanstalk-console"

  service_websocket:
    build:
      context: ./data/websocket/
    container_name: "service_websocket"
    ports:
      - "3000:3000"
    networks:
      - dev_stack_net

  redis:
    image: redis:3.2-alpine
    container_name: "service_websocket_redis"
    ports:
      - "6379:6379"
    networks:
      - dev_stack_net

networks:
  dev_stack_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.80.0.0/16
          gateway: 172.80.0.80
