# defaultEntryPoints must be at the top because it should not be in any table below
defaultEntryPoints = ["http"]

[web]
# Port for the status page
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "dev.com"
watch = true
exposedbydefault = false